# Generated by Django 4.2.14 on 2024-07-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tb1_Authentication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Empcode", models.IntegerField()),
                ("username", models.CharField(default="", max_length=50)),
                ("password", models.CharField(default="", max_length=50)),
                ("is_active", models.ImageField(null=True, upload_to="")),
            ],
        ),
    ]
