# Generated by Django 4.2.14 on 2024-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_alter_tb1_authentication_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tb1_authentication",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tb1_authentication",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="tb1_authentication",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
