# Generated by Django 4.2.14 on 2024-07-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_tb1_authentication_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tb1_authentication",
            name="is_staff",
        ),
    ]
