# Generated by Django 4.2.14 on 2024-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0004_remove_tb1_authentication_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=100)),
                ("purchase_date", models.DateField()),
                ("complaint_details", models.TextField()),
            ],
        ),
    ]
