# Generated by Django 4.2.14 on 2024-07-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0005_complaint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Complaint",
        ),
    ]
